Repository redhat-developer/quarkus-ls, pull requests merged in 2022-08, with the labels that each got.

#688 Create a code action class per error code.
  qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/hello.qute.html
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/AbstractQuteCodeAction.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionRequest.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedNamespace.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedObject.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedSectionTag.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownMethod.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownProperty.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/DiagnosticDataFactory.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/JavaBaseTypeOfPartData.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteDiagnosticContants.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/UnknownPropertyData.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayLengthValueResolverTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArraySizeValueResolverTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayTakeLastValueResolverTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayTakeValueResolverTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/builtin/OrValueResolverTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInfixNotationTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSeverityTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithCheckedTemplateTest.java
Labels: enhancement, debt

#694 Do not give CodeActions for stale diagnostics
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ValidatorDelayer.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
Labels: bug

#695 Update dependencies to latest versions.
  quarkus.jdt.ext/pom.xml
  quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
  qute.jdt/pom.xml
Labels: build, dependencies

#685 Added Qute CodeAction(s) for similar text suggestions for `UnknownMethod`
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownMethod.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
Labels: enhancement, code action, qute
