Repository redhat-developer/quarkus-ls, pull requests merged in 2022-07, with the labels that each got.

#668 Adapt to new version of m2e in JDT-LS
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
  quarkus.jdt.ext/pom.xml
  qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
  qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
  qute.jdt/pom.xml
Labels: build, dependencies

#669 Update Jenkinsfile to use Java 17
  Jenkinsfile
Labels: build

#679 Fix cancel support with CompletableFuture compose
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ModelTextDocuments.java
Labels: bug
