Repository redhat-developer/quarkus-ls, pull requests merged in 2024-10, with the labels that each got.

#999 fix: add languageId filter for options similar to microprofile
  quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/QuarkusLanguageIds.java
  quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusRegistrationConfiguration.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/QuteLanguageIds.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
Labels: bug, quarkus-ls, properties

#1002 chore: bump to 0.20.0
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
  quarkus.jdt.ext/pom.xml
  quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
  qute.jdt/com.redhat.qute.jdt.site/pom.xml
  qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
  qute.jdt/com.redhat.qute.jdt.test/pom.xml
  qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
  qute.jdt/com.redhat.qute.jdt/pom.xml
  qute.jdt/pom.xml
  qute.ls/com.redhat.qute.ls/pom.xml
Labels: build

#1007 False positive error with param name and user tag
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
Labels: bug, qute, template-file

#1008 TemplateExtension match any support
  qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/BaseQuteProject.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/DocumentPage.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/Paginator.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqCollection.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqCollections.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqDataModel.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqProject.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/Site.json
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/roq/RoqCompletionsTest.java
  qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/roq/RoqDiagnosticsTest.java
Labels: bug

#1006 Improve the Target platform for JDT Extension components.
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
  quarkus.jdt.ext/pom.xml
  qute.jdt/com.redhat.qute.jdt.test/pom.xml
  qute.jdt/pom.xml
Labels: build

#1003 `quarkus.rest.path` support
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/config-properties/.classpath
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/config-properties/pom.xml
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/QuarkusConstants.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/ConfigPhase.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/ConfigProperties.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/NamingStrategy.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigRootProvider.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
  quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/io/quarkus/arc/config/ConfigProperties.java
  quarkus.jdt.ext/pom.xml
Labels: performance

#1004 chore: changelog 0.20.0
  CHANGELOG.md
Labels: documentation
